version: '3.4'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - .env.docker
    volumes:
      - .:/app
    ports:
      - "5050:3000"
    depends_on:
      - db
    entrypoint: "./docker-entrypoint.sh"

volumes:
  postgres_data: {}